//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MouseJiggler.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class XamlResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal XamlResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MouseJiggler.Properties.XamlResources", typeof(XamlResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De-/Activate.
        /// </summary>
        public static string Menu_DeActivate {
            get {
                return ResourceManager.GetString("Menu_DeActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Menu_Settings {
            get {
                return ResourceManager.GetString("Menu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutdown.
        /// </summary>
        public static string Menu_Shutdown {
            get {
                return ResourceManager.GetString("Menu_Shutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle.
        /// </summary>
        public static string Mode_Circle {
            get {
                return ResourceManager.GetString("Mode_Circle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smooth.
        /// </summary>
        public static string Mode_Smooth {
            get {
                return ResourceManager.GetString("Mode_Smooth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zen.
        /// </summary>
        public static string Mode_Zen {
            get {
                return ResourceManager.GetString("Mode_Zen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zig Zag.
        /// </summary>
        public static string Mode_ZigZag {
            get {
                return ResourceManager.GetString("Mode_ZigZag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autostart jiggle.
        /// </summary>
        public static string Settings_Autostart {
            get {
                return ResourceManager.GetString("Settings_Autostart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance:.
        /// </summary>
        public static string Settings_Distance {
            get {
                return ResourceManager.GetString("Settings_Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jiggle interval:.
        /// </summary>
        public static string Settings_JiggleInterval {
            get {
                return ResourceManager.GetString("Settings_JiggleInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jiggle mode:.
        /// </summary>
        public static string Settings_JiggleMode {
            get {
                return ResourceManager.GetString("Settings_JiggleMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Settings_OkButtonText {
            get {
                return ResourceManager.GetString("Settings_OkButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }
    }
}
